### PR TITLE
fix: wire:key consistency

### LINKED ISSUE #3000: The "category" field breaks after changing the payment method
When I change the plugin type from **Not paid** to **Paid** and return to **Not paid** the `category` field breaks, take a look to the demo video below.

https://user-images.githubusercontent.com/6197875/176866253-c1246f49-61bf-40bd-8d9f-8f7b0882d8a2.mp4

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #3000.

### CODE REVIEW

File: packages/tables/src/Testing/TestsRecords.php [hunk 1]
```diff
@@ -27,7 +27,7 @@ function ($record) use ($livewire) {
                         $record = $livewire->getTableRecordKey($record);
                     }
 
-                    return "wire:key=\"table.records.{$record}\"";
+                    return "{$livewire->id}.table.records.{$record}";
```
Comment (Saifallak) [inline packages/tables/src/Testing/TestsRecords.php:30]: @danharrin isn't this wrong?, where is wire:key=xxxx

Comment (danharrin) [reply packages/tables/src/Testing/TestsRecords.php:30]: No this isn't an issue, I want to decouple the tests from this specific attribute in the view. It still works fine for you, right?

Comment (Saifallak) [reply packages/tables/src/Testing/TestsRecords.php:30]: Didn't have a chance to test,..
Just thought it was a mistypo to remove wirekey.
